{
 "title": "Dashboard 1",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Ledger Fetches",
   "type": "graph",
   "description": "Count of inbound ledger fetches averaged",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "stats.*.ledger_fetches" }
   ]
  },
  {
   "title": "Heart Beat",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.timers.*.jobq.heartbeat.mean"
    },
    {
     "target": "stats.timers.*.jobq.heartbeat_q.mean"
    }
   ]
  },
  {
   "title": "Job Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "stats.*.jobq.job_count" }
   ]
  },
  {
   "title": "Advance Ledger",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.timers.*.jobq.advanceLedger.mean"
    },
    {
     "target": "stats.timers.*.jobq.advanceLedger_q.mean"
    }
   ]
  }
 ]
}